[package]
name = "md_static_site_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.4.0"
pulldown-cmark = "0.9.2"
tera = "1.17.1"
anyhow = "1.0.75"
serde = { version = "1.0", features = ["derive"] }