name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.toml"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Static Site
        run: |
          cargo build --release
          cargo run

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: main
